// This file is generated automatically by Next.js
// Do not edit this file manually

type AppRoutes = "/" | "/admin/preview-v5-1/[id]" | "/admin/preview-v5/[id]" | "/admin/preview/[id]" | "/complete-signup" | "/dashboard" | "/discover" | "/login" | "/report/[id]" | "/sample" | "/sample/[slug]" | "/signup" | "/submit"
type AppRouteHandlerRoutes = "/api/assign-submission" | "/api/claim-report" | "/api/complete-signup" | "/api/contact-writer" | "/api/discover" | "/api/evaluate" | "/api/evaluations/[id]/edit" | "/api/scripts/[id]/like" | "/api/scripts/[id]/visibility" | "/api/send-upgrade-email" | "/api/send-welcome" | "/api/stripe/checkout" | "/api/stripe/portal" | "/api/stripe/webhook" | "/api/submissions/[id]/hide" | "/auth/callback"
type PageRoutes = never
type LayoutRoutes = "/" | "/report/[id]"
type RedirectRoutes = never
type RewriteRoutes = never
type Routes = AppRoutes | PageRoutes | LayoutRoutes | RedirectRoutes | RewriteRoutes | AppRouteHandlerRoutes


interface ParamMap {
  "/": {}
  "/admin/preview-v5-1/[id]": { "id": string; }
  "/admin/preview-v5/[id]": { "id": string; }
  "/admin/preview/[id]": { "id": string; }
  "/api/assign-submission": {}
  "/api/claim-report": {}
  "/api/complete-signup": {}
  "/api/contact-writer": {}
  "/api/discover": {}
  "/api/evaluate": {}
  "/api/evaluations/[id]/edit": { "id": string; }
  "/api/scripts/[id]/like": { "id": string; }
  "/api/scripts/[id]/visibility": { "id": string; }
  "/api/send-upgrade-email": {}
  "/api/send-welcome": {}
  "/api/stripe/checkout": {}
  "/api/stripe/portal": {}
  "/api/stripe/webhook": {}
  "/api/submissions/[id]/hide": { "id": string; }
  "/auth/callback": {}
  "/complete-signup": {}
  "/dashboard": {}
  "/discover": {}
  "/login": {}
  "/report/[id]": { "id": string; }
  "/sample": {}
  "/sample/[slug]": { "slug": string; }
  "/signup": {}
  "/submit": {}
}


export type ParamsOf<Route extends Routes> = ParamMap[Route]

interface LayoutSlotMap {
  "/": never
  "/report/[id]": never
}


export type { AppRoutes, PageRoutes, LayoutRoutes, RedirectRoutes, RewriteRoutes, ParamMap, AppRouteHandlerRoutes }

declare global {
  /**
   * Props for Next.js App Router page components
   * @example
   * ```tsx
   * export default function Page(props: PageProps<'/blog/[slug]'>) {
   *   const { slug } = await props.params
   *   return <div>Blog post: {slug}</div>
   * }
   * ```
   */
  interface PageProps<AppRoute extends AppRoutes> {
    params: Promise<ParamMap[AppRoute]>
    searchParams: Promise<Record<string, string | string[] | undefined>>
  }

  /**
   * Props for Next.js App Router layout components
   * @example
   * ```tsx
   * export default function Layout(props: LayoutProps<'/dashboard'>) {
   *   return <div>{props.children}</div>
   * }
   * ```
   */
  type LayoutProps<LayoutRoute extends LayoutRoutes> = {
    params: Promise<ParamMap[LayoutRoute]>
    children: React.ReactNode
  } & {
    [K in LayoutSlotMap[LayoutRoute]]: React.ReactNode
  }

  /**
   * Context for Next.js App Router route handlers
   * @example
   * ```tsx
   * export async function GET(request: NextRequest, context: RouteContext<'/api/users/[id]'>) {
   *   const { id } = await context.params
   *   return Response.json({ id })
   * }
   * ```
   */
  interface RouteContext<AppRouteHandlerRoute extends AppRouteHandlerRoutes> {
    params: Promise<ParamMap[AppRouteHandlerRoute]>
  }
}
