"use client"

import { useState } from "react"
import { useRouter } from "next/navigation"

/**
 * Shows a banner when the current evaluation was generated by an older
 * prompt version. Clicking "Update" triggers a re-evaluation and redirects
 * to the new report. While running, takes over the full viewport with a
 * loading overlay so the user knows something real is happening.
 */
export function RerunBanner({ submissionId }: { submissionId: string }) {
  const [state, setState] = useState<"idle" | "running" | "error">("idle")
  const [errorMsg, setErrorMsg] = useState<string | null>(null)
  const router = useRouter()

  async function handleRerun() {
    setState("running")
    setErrorMsg(null)
    try {
      const res = await fetch("/api/rerun-evaluation", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ submission_id: submissionId }),
      })
      // Handle non-JSON responses (e.g. Vercel 504 timeout page)
      const contentType = res.headers.get("content-type") ?? ""
      if (!contentType.includes("application/json")) {
        throw new Error(`Server returned ${res.status} (non-JSON). The evaluation may have timed out.`)
      }
      const data = await res.json()
      if (!res.ok) {
        throw new Error(data.error ?? `Failed (${res.status})`)
      }
      if (data.status === "already_current") {
        router.refresh()
        return
      }
      router.push(`/report/${data.evaluation_id}`)
    } catch (err: any) {
      console.error("Rerun failed:", err)
      setErrorMsg(err?.message ?? "Unknown error")
      setState("error")
    }
  }

  // Full-page loading overlay while rerunning
  if (state === "running") {
    return (
      <div className="fixed inset-0 z-[9999] flex items-center justify-center bg-white/95 backdrop-blur-sm">
        <div className="flex flex-col items-center gap-5 px-6 text-center max-w-sm">
          {/* Spinner */}
          <div className="w-10 h-10 border-[3px] border-gray-200 border-t-gray-800 rounded-full animate-spin" />
          <div>
            <p className="text-[17px] font-semibold text-gray-900 m-0">
              Re-running evaluation
            </p>
            <p className="text-[14px] text-gray-500 m-0 mt-2 leading-relaxed">
              This takes 30–60 seconds. Your report will refresh automatically when it's ready.
            </p>
          </div>
        </div>
      </div>
    )
  }

  // Error state — let them retry
  if (state === "error") {
    return (
      <div
        className="rounded-xl px-5 py-4 mb-6 flex items-center justify-between gap-4 flex-wrap"
        style={{ background: "#fef2f2", border: "1px solid #fecaca" }}
      >
        <div className="flex-1 min-w-[200px]">
          <p className="text-[14px] font-semibold text-red-800 m-0 leading-tight">
            Update failed
          </p>
          <p className="text-[13px] text-red-600 m-0 mt-1 leading-snug">
            {errorMsg ?? "Something went wrong."} Please try again.
          </p>
        </div>
        <button
          onClick={handleRerun}
          className="px-4 py-2 rounded-lg text-[13px] font-semibold transition-all bg-red-600 hover:bg-red-700 text-white"
        >
          Retry
        </button>
      </div>
    )
  }

  // Idle — show the update banner
  return (
    <div
      className="rounded-xl px-5 py-4 mb-6 flex items-center justify-between gap-4 flex-wrap"
      style={{
        background: "var(--gem-gray-900, #f8f8f8)",
        border: "1px solid var(--gem-gray-700, #e2e2e2)",
      }}
    >
      <div className="flex-1 min-w-[200px]">
        <p className="text-[14px] font-semibold text-[var(--gem-gray-50)] m-0 leading-tight">
          Updated evaluation available
        </p>
        <p className="text-[13px] text-[var(--gem-gray-300)] m-0 mt-1 leading-snug">
          A newer version of our scoring model is available. Update to get the latest analysis.
        </p>
      </div>
      <button
        onClick={handleRerun}
        className="px-4 py-2 rounded-lg text-[13px] font-semibold transition-all hover:opacity-90"
        style={{
          background: "var(--gem-gray-50, #1a1a1a)",
          color: "#fff",
        }}
      >
        Update report
      </button>
    </div>
  )
}
