"use client"

import { useState } from "react"
import { useRouter } from "next/navigation"

/**
 * Shows a banner when the current evaluation was generated by an older
 * prompt version. Clicking "Update" triggers a re-evaluation and redirects
 * to the new report.
 */
export function RerunBanner({ submissionId }: { submissionId: string }) {
  const [state, setState] = useState<"idle" | "running" | "error">("idle")
  const router = useRouter()

  async function handleRerun() {
    setState("running")
    try {
      const res = await fetch("/api/rerun-evaluation", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ submission_id: submissionId }),
      })
      const data = await res.json()
      if (!res.ok) {
        throw new Error(data.error ?? "Failed to re-run evaluation")
      }
      if (data.status === "already_current") {
        // Edge case — already up to date, just refresh
        router.refresh()
        return
      }
      // Redirect to the new evaluation report
      router.push(`/report/${data.evaluation_id}`)
    } catch (err: any) {
      console.error("Rerun failed:", err)
      setState("error")
    }
  }

  return (
    <div
      className="rounded-xl px-5 py-4 mb-6 flex items-center justify-between gap-4 flex-wrap"
      style={{
        background: "var(--gem-gray-900, #f8f8f8)",
        border: "1px solid var(--gem-gray-700, #e2e2e2)",
      }}
    >
      <div className="flex-1 min-w-[200px]">
        <p className="text-[14px] font-semibold text-[var(--gem-gray-50)] m-0 leading-tight">
          Updated evaluation available
        </p>
        <p className="text-[13px] text-[var(--gem-gray-300)] m-0 mt-1 leading-snug">
          A newer version of our scoring model is available. Update to get the latest analysis.
        </p>
      </div>
      <button
        onClick={handleRerun}
        disabled={state === "running"}
        className="px-4 py-2 rounded-lg text-[13px] font-semibold transition-all disabled:opacity-60"
        style={{
          background: "var(--gem-gray-50, #1a1a1a)",
          color: "#fff",
        }}
      >
        {state === "running" ? "Updating…" : state === "error" ? "Retry" : "Update report"}
      </button>
    </div>
  )
}
