import type { Metadata } from 'next'
import { createClient } from '@/lib/supabase-server'
import Nav from '@/components/nav'
import { SampleGrid, type SampleGridItem } from '@/components/sample/sample-grid'
import { normalizeEvaluation, type Tier, type ScriptEvaluation, type ScriptSubmission, type GEMEvaluation } from '@/types'

export const dynamic = 'force-dynamic'

export const metadata: Metadata = {
  title: 'Sample Reports — Produced Screenplays Scored by GEM',
  description:
    "See how GEM scores real, produced screenplays — Breaking Bad, Inception, The Sopranos, Game of Thrones and more. Full reports, no signup, free to read.",
  alternates: { canonical: 'https://www.gem.studio/sample' },
  openGraph: {
    title: 'GEM Sample Reports — Produced Screenplays Scored',
    description:
      'Breaking Bad, Inception, The Sopranos and more — scored by GEM. Full reports, no paywall.',
    url: 'https://www.gem.studio/sample',
    type: 'website',
  },
}

interface PageProps {
  searchParams: Promise<{ type?: string }>
}

type SampleRow = ScriptSubmission & {
  sample_slug: string | null
  sample_author: string | null
  sample_year: number | null
  sample_genre: string | null
  sample_type: string | null
  is_sample: boolean | null
  script_evaluations: ScriptEvaluation[] | null
}

export default async function SampleIndexPage({ searchParams }: PageProps) {
  const { type } = await searchParams
  const supabase = await createClient()

  const { data: rows } = await supabase
    .from('script_submissions')
    .select(`
      id, title, sample_slug, sample_author, sample_year, sample_genre, sample_type, is_sample,
      script_evaluations ( id, weighted_score, tier, evaluation, created_at )
    `)
    .eq('is_sample', true)
    .eq('status', 'completed')

  const mapped: (SampleGridItem | null)[] = (rows ?? []).map((r): SampleGridItem | null => {
    const row = r as unknown as SampleRow
    const ev = row.script_evaluations?.[0]
    if (!ev) return null
    const rawEval = ev.evaluation as GEMEvaluation
    const { classification } = normalizeEvaluation(rawEval)
    const headline =
      rawEval.whats_special?.headline ??
      rawEval.development_assessment?.overall_take ??
      null
    return {
      slug: row.sample_slug!,
      title: row.title,
      author: row.sample_author ?? 'Unknown',
      year: row.sample_year ?? null,
      type: row.sample_type ?? 'Feature',
      genre: row.sample_genre ?? classification.genre_primary ?? null,
      weighted_score: ev.weighted_score,
      tier: ev.tier as Tier,
      tone: classification.tone ?? null,
      logline: headline,
    }
  })
  const allSamples: SampleGridItem[] = mapped
    .filter((x): x is SampleGridItem => x !== null)
    .sort((a, b) => b.weighted_score - a.weighted_score)

  const tvCount = allSamples.filter((s) => s.type === 'TV Pilot').length
  const featureCount = allSamples.filter((s) => s.type === 'Feature').length
  const totalCount = allSamples.length

  const samples =
    type === 'tv'
      ? allSamples.filter((s) => s.type === 'TV Pilot')
      : type === 'feature'
        ? allSamples.filter((s) => s.type === 'Feature')
        : allSamples

  return (
    <>
      <Nav />
      <div className="max-w-5xl mx-auto px-4 py-8">
        <div className="mb-6">
          <p className="text-xs uppercase tracking-widest text-[var(--gem-gold)] font-medium mb-2">
            Sample Library
          </p>
          <h1 className="text-3xl sm:text-4xl font-bold mb-2 font-[family-name:var(--font-display)]">
            Produced screenplays, scored by GEM
          </h1>
          <p className="text-sm text-[var(--gem-gray-400)] max-w-2xl leading-relaxed">
            See how GEM reads real, produced scripts — Breaking Bad, Inception, The Sopranos, Game of Thrones and more.
            Every report is generated by the same engine that will score your own script. Free to read, no signup.
          </p>
        </div>

        <div className="flex items-center gap-2 mb-6">
          <FilterTab href="/sample" label={`All (${totalCount})`} active={!type} />
          <FilterTab href="/sample?type=tv" label={`TV Pilots (${tvCount})`} active={type === 'tv'} />
          <FilterTab href="/sample?type=feature" label={`Features (${featureCount})`} active={type === 'feature'} />
        </div>

        {samples.length > 0 ? (
          <SampleGrid samples={samples} />
        ) : (
          <div className="text-center py-20">
            <p className="text-[var(--gem-gray-400)] text-sm">No samples match this filter.</p>
          </div>
        )}

        <div className="mt-10 p-5 rounded-xl border border-[var(--gem-gray-700)] bg-[var(--gem-gray-900)]/50">
          <p className="text-sm text-[var(--gem-gray-300)] leading-relaxed">
            <span className="font-semibold text-[var(--gem-white)]">Want to see your script on this list?</span>{' '}
            GEM scores your screenplay with the same engine in under a minute — first eval is free.{' '}
            <a href="/submit" className="text-[var(--gem-accent)] hover:underline font-medium">
              Score your screenplay →
            </a>
          </p>
        </div>
      </div>
    </>
  )
}

function FilterTab({ href, label, active }: { href: string; label: string; active: boolean }) {
  return (
    <a
      href={href}
      className={`px-3 py-1.5 rounded-lg text-xs font-medium transition-colors ${
        active
          ? 'bg-[var(--gem-accent)] text-white'
          : 'bg-[var(--gem-gray-800)] text-[var(--gem-gray-300)] hover:bg-[var(--gem-gray-700)]'
      }`}
    >
      {label}
    </a>
  )
}
