var R=require("../../chunks/ssr/[turbopack]_runtime.js")("server/app/_global-error/page.js")
R.c("server/chunks/ssr/[root-of-the-server]__11beuav._.js")
R.c("server/chunks/ssr/0c5b_next_dist_esm_build_templates_app-page_0j8nxv..js")
R.c("server/chunks/ssr/[root-of-the-server]__0c6g18y._.js")
R.c("server/chunks/ssr/[root-of-the-server]__124omjw._.js")
R.c("server/chunks/ssr/0c5b_0xzqxey._.js")
R.c("server/chunks/ssr/0c5b_next_dist_client_components_builtin_global-error_0a43api.js")
R.c("server/chunks/ssr/09j6_Selznick_3_gem-app__next-internal_server_app__global-error_page_actions_0x~hb2s.js")
R.m(86582)
module.exports=R.m(86582).exports
